// auth

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// 
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_LOADING = "CREATE_DATA_LOADING";
export const CREATE_DATA_FAILED = "CREATE_DATA_FAILED";

export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_LOADING = "UPDATE_DATA_LOADING";
export const UPDATE_DATA_FAILED = "UPDATE_DATA_FAILED";

export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_LOADING = "DELETE_DATA_LOADING";
export const DELETE_DATA_FAILED = "DELETE_DATA_FAILED";


export const SUCCESS = "SUCCESS";
export const FAILED = "FAILED";
export const LOADING = "LOADING";


// login
// get profile
// log out